### ISSUE TITLE
Safari 10 /11 problem with if (!await get(something)). Exclamation point and await (async) indigestion.

### ISSUE THREAD

**Issue by ghost** [ember-cli/ember-cli-uglify#27] opened 2017-09-11 00:32 UTC
I'm on latest stable of everything (Node 8.4.0, npm 5.4.1, ember-source 2.15.0, ember-cli 2.15.1).
I tried both with `ember-cli-uglify v2.0.0-beta.1` and `v2.0.0-beta.2`.
I tried with and without mangle for _damned_ Safari 10 (in beta.2 it is default).

I have this code:

```javascript
let myPromiseContent = await get(category, "myPromise").content;
if (!myPromiseContent) {
  console.log('ByeBye Safari!');
}
```

`myPromiseContent` is a number. And I need to check if it is `0` to print that `console.log()`.

In Safari (10 and 11, `with Technology preview 39a`) it blocks page rendering and says:

`SyntaxError: Unexpected identifier 'a'. Expected ')' to end an 'if' condition.`

The line is this one:

`})), !await a(t, "myPromise").content) {`

Of course if I remove `await` from my source code or check it like this:

`if (myPromiseContent === 0) {`

**it works again**.

But I can't use "!" with an `await`? Is it generally wrong? "eslint" doesn't warn me about this.

**Am I wrong?**

**Comment by ghost** [comment] 2017-09-12 12:45
@rwjblue What do you think about this: https://github.com/mishoo/UglifyJS2/issues/2308#issuecomment-328839005 ?

**Comment by rwjblue** [comment] 2017-09-12 13:39
Glad you confirmed it was an upstream issue.  Since there really isn't anything we can do here in ember-cli-uglify, I am going to close this issue.

**Closed as completed by rwjblue** 2017-09-12 13:39 UTC

**Comment by ghost** [comment] 2017-09-12 14:08
My question was to understand your precious opinion about ES7 and Safari 10. I'm using also ember-cli-babel with target.js file. What do you think about? Ani iPhone, iPad, iOS device is out??!

**Comment by rwjblue** [comment] 2017-09-12 14:44
Yep, browsers always have bugs. 😸  Not really anything we can do about it on Safari though.

In theory, we could start a discussion around updating caniuse.com's database for async/await to exclude Safari 10.  Once updated (and babel-preset-env updates as well) we would automatically transpile `async` / `await` down to regenerator usage (and ship regenerator runtime to the browser).

Another option for you is to add `async`/`await` to `include` (which will force `async` / `await` to be transpiled with current versions of ember-cli-babel/babel-preset-env). That would look like:

```js
let app = new EmberApp(defaults, {
  babel: {
    include: ['transform-async-to-generator']
  }
});
```

**Comment by ghost** [comment] 2017-09-12 15:19
How can we update caniuse.com's DB?

Can you explain better the latter ("include") option, please?

**Comment by rwjblue** [comment] 2017-09-12 15:46
You can read about how `include` works with `babel-preset-env` [here](https://github.com/babel/babel-preset-env#options).

**Comment by ghost** [comment] 2017-09-13 00:26
Dear @rwjblue, as always your advice has been very useful. Using the "include" method in ember-cli-build.js like this:

```
    babel: {
      include: ["transform-async-to-generator"]
    }
```

works good on Safari 10 and my `app.js` it's not much bigger.

I still have this in my `target.js` anyway:

```
module.exports = {
  browsers: [
    'last 1 Chrome versions',
    'last 1 Firefox versions',
    'last 1 Safari versions',
    'last 1 Edge versions'
  ]
};
```

What can we do with this? I have to write to caniuse? What do you advise?
