### ISSUE TITLE
Failed to open file '/data/data/com.ribedevs.buildup/code_cache/.overlay/base.apk/resources.arsc': No such file or directory

### ISSUE THREAD

**Issue by Muhammad-ruman** [ember-cli/ember-cli-uglify#299] opened 2021-12-18 11:45 UTC
Failed to open file '/data/data/com.ribedevs.buildup/code_cache/.overlay/base.apk/resources.arsc': No such file or directory

How do I solve this >???

2021-12-16 14:51:21.660 31402-31402/com.ribedevs.buildup E/ibedevs.buildu: Failed to open file '/data/data/com.ribedevs.buildup/code_cache/.overlay/base.apk/resources.arsc': No such file or directory

**Comment by bertdeblock** [comment] 2023-01-29 10:25
Based on the issue title and description, I can't tell if this issue is actually related to / caused by `ember-cli-terser`.
Closing for now. Please reopen with more info / details if I'm mistaken.

**Closed as completed by bertdeblock** 2023-01-29 10:25 UTC
