### ISSUE TITLE
Template literals defined outside of exports are not handled properly

### ISSUE THREAD

**Issue by ggayowsky** [ember-cli/ember-cli-uglify#32] opened 2017-10-25 13:52 UTC
After uprading to ember-cli-uglify version 2.0.0, I noticed that my production build was starting to break with this error `this.__defineNonEnumerable is not a function`.

After stepping through the minified & uglified code, the culprit seems to be template literals defined outside of any export object.

It don't know how to create a twiddle showing the problem, however, below is a simplified object that  can successfully reproduce the bug.

```
import EmberObject from '@ember/object';

const TEST_PROP = `THIS WILL BREAK EMBER-CLI-UGLIFY`;

export default EmberObject.extend({
    testProp: TEST_PROP
});
```
 
ends up getting minified & uglified to

```
efineday("rspace/models/uglify-object-break", ["exports"], function(e) {
    Object.defineProperty(e, "__esModule", {
        value: !0
    })
    var t = Ember.Object`THIS WILL BREAK EMBER-CLI-UGLIFY`
    e.default = t.extend({
        testProp: "THIS WILL BREAK EMBER-CLI-UGLIFY"
    })
}),
```

As you can see, the const TEST_PROP is being replaced inside the class with the string, however, it is failing to strip template literal outside the extend.

Javascript thus thinks the line ``Ember.Object`THIS WILL BREAK EMBER-CLI-UGLIFY` `` is a tagged template literal leading to the error `this.__defineNonEnumerable is not a function`

**Comment by ggayowsky** [comment] 2017-10-25 13:56
There are plenty of workarounds to this issue.

- Use string concatenation instead of template literals
- Have the template literal be defined where it will be used (in the example above inside the object)
- export the template literal

**Comment by rwjblue** [comment] 2017-10-25 16:39
Yikes!! This sounds like an uglify bug to me, but I'm having a hard time reproducing it locally.

Can you share the `define` statement contents of that module in development builds?

**Comment by ggayowsky** [comment] 2017-10-25 16:48
In the dev build (or production with uglify disabled), this is what I see:

```
efineday('rspace/models/uglift-object-break', ['exports'], function (exports) {
    'use strict';

    Object.defineProperty(exports, "__esModule", {
        value: true
    });
    var EmberObject = Ember.Object;


    const TEST_PROP = `THIS WILL BREAK EMBER-CLI-UGLIFY`;

    exports.default = EmberObject.extend({
        testProp: TEST_PROP
    });
});
```

**Comment by ggayowsky** [comment] 2017-10-25 16:53
I should probably include my targets.js and my package.json.

targets.js
```
/* eslint-env node */
module.exports = {
  browsers: [
    'last 5 Chrome versions',
    'last 5 Firefox versions'
  ]
};
```

Package.json
```
{
  "version": "0.0.0",
  "private": true,
  "description": "Small description goes here",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": "",
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-cli": "~2.16.2",
    "ember-cli-amd": "0.4.8",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.6.0",
    "ember-cli-content-security-policy": "0.6.1",
    "ember-cli-dependency-checker": "^2.0.0",
    "ember-cli-eslint": "^4.0.0",
    "ember-cli-htmlbars": "^2.0.1",
    "ember-cli-htmlbars-inline-precompile": "^1.0.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-qunit": "^4.0.0",
    "ember-cli-sass": "6.1.2",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^2.0.0",
    "ember-component-css": "^0.3.5",
    "ember-concurrency": "0.8.7",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.0.0",
    "ember-resolver": "^4.0.0",
    "ember-sinon": "^0.7.0",
    "ember-sinon-qunit": "^1.6.0",
    "ember-source": "~2.16.0",
    "ember-truth-helpers": "^2.0.0",
    "eslint-config-semistandard": "^11.0.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-plugin-ember": "^4.5.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.1.1",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^3.0.1",
    "loader.js": "^4.2.3"
  },
  "engines": {
    "node": "^4.5 || 6.* || >= 7.*"
  }
}
```

**Comment by ggayowsky** [comment] 2017-10-25 17:09
When I included ie-9 in my targets.js, I no longer see this issue. I am guessing that is because babel converts the template strings to string concatenation before the uglify runs

**Comment by rwjblue** [comment] 2017-10-25 17:25
OK, I can now reproduce, thank you!

Given this input:


```js
function callback(exports) {
  var foo = global.foo;

  const TEST_PROP = `some template string`;

  exports.default = foo({
    testProp: TEST_PROP,
  });
}
```

Compiling with the latest `uglify-es` version using the same options that this library uses by default:

```
uglifyjs --compress --beautify beautify=false,semicolons=false --mangle --  test.js
```

We get the following (invalid) output:

```js
function callback(I){var L=global.foo
`some template string`
I.default=L({testProp:"some template string"})}
```

@ggayowsky - Would you mind reporting to https://github.com/mishoo/UglifyJS2/issues with the minimal repro above?

**Comment by ggayowsky** [comment] 2017-10-25 17:53
Done.

https://github.com/mishoo/UglifyJS2/issues/2401

**Comment by rwjblue** [comment] 2017-10-28 16:51
Closing, looks like the upstream issue is closed...

**Closed as completed** 2017-10-28 16:52 UTC
